/* 실제 TS API 모듈을 실행한다. 네트워크 응답은 합성이며 실모델 평가가 아니다. */
const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..');
class ApiError extends Error{constructor(m,status,code){super(m);this.status=status;this.code=code;}}
function load(handler){const s=fs.readFileSync(path.join(root,'lib/qualification-graph-api.ts'),'utf8');const code=ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const m={exports:{}};new Function('require','module','exports',code)(()=>({apiFetch:handler,ApiError}),m,m.exports);return m.exports;}
const comparison={contract_version:'qualification-graph-comparison-v1',case_id:'C',baseline_run_id:'B',current_run_id:'A',comparison_status:'COMPLETE',changes:[],counts:{},issues:[],db_writes:false,eligibility_change_asserted:false};
test('comparison GET has explicit IDs and no store',async()=>{let call;const a=load(async(...args)=>{call=args;return{ok:true,json:async()=>comparison};});await a.compareGraphs('C','B','A');assert.equal(call[1].method,'GET');assert.equal(call[1].cache,'no-store');assert.equal(new URL('http://test'+call[0]).searchParams.get('baseline_run_id'),'B');});
for(const [name,edit] of [['case',d=>d.case_id='X'],['base',d=>d.baseline_run_id='X'],['current',d=>d.current_run_id='X'],['writes',d=>d.db_writes=true],['verdict',d=>d.eligibility_change_asserted=true],['counts',d=>d.counts.MODIFIED=1]])test(`comparison rejects ${name}`,()=>{const d=structuredClone(comparison);edit(d);assert.throws(()=>load().parseGraphComparison(d,'C','B','A'));});
for(const status of [403,404,409,503])test(`HTTP ${status} is not unchanged`,async()=>{const a=load(async()=>({ok:false,status,json:async()=>({error:{message:'확인 필요',code:'ERR'}})}));await assert.rejects(a.compareGraphs('C','B','A'),e=>e.status===status);});
test('same run rejects before network',async()=>{await assert.rejects(load(()=>assert.fail()).compareGraphs('C','A','A'));});
test('analysis sends role only, no company or budget',async()=>{let call;const a=load(async(...args)=>{call=args;return{ok:true,json:async()=>({id:'R',contract_version:'qualification-document-graph-v1'})};});await a.analyzeGraph('C','current');assert.equal(call[1].method,'POST');assert.deepEqual(JSON.parse(call[1].body),{version_role:'current'});});
test('rejudge uses saved graph and explicit date',async()=>{let call;const a=load(async(...args)=>{call=args;return{ok:true,json:async()=>({graph_run_id:'A',result:{case_id:'C',reference_date:'2026-09-15',semantic_accuracy_verified:false}})};});await a.judgeGraph('C','A','2026-09-15');assert.deepEqual(JSON.parse(call[1].body),{graph_run_id:'A',reference_date:'2026-09-15'});});
test('missing date does not issue request',async()=>{await assert.rejects(load(()=>assert.fail()).judgeGraph('C','A',''));});
test('options preserve copilot disconnected',async()=>{const a=load(async()=>({ok:true,json:async()=>({contract_version:'qualification-graph-options-v1',enabled:false,copilot_connected:false})}));assert.equal((await a.graphOptions()).enabled,false);});
test('graph TSX parses without a copilot import',()=>{const p='app/qualification-graph/page.tsx',s=fs.readFileSync(path.join(root,p),'utf8');assert.deepEqual(ts.createSourceFile(p,s,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX).parseDiagnostics,[]);assert(!s.includes("from '@/components/copilot"));});
